<?php return array (
  'layout' => 'none',
  'primary' => 'primary',
  'secondary' => 'secondary',
  'responsive' => true,
  'responsive_breakpoint_2' => '960px',
  'responsive_breakpoint_3' => '420px',
  'description' => 'Business & Financial WordPress Theme',
  'keywords' => 'xtra,business,finance,WordPress,WP,Theme',
  'lazyload' => true,
  'remove_query_args' => true,
  'site_color' => '#4d61ff',
  'site_width' => '1270px',
  'dark' => true,
  '_css_body' => 'background-color:#151719;',
  '_css_layout_1' => 'border-style:solid;border-radius:4px;',
  '_css_buttons' => 'font-weight:700;padding:12px 25px;border-style:solid;border-radius:50px;box-shadow:0px 0px 0px 0px #000;',
  '_css_buttons_hover' => 'color:#4d61ff;background-color:#ffffff;',
  '_css_widgets' => 'background-color:rgba(255,255,255,0.02);margin-bottom:30px;border-radius:10px;',
  '_css_widgets_headline' => 'font-size:16px;color:#ffffff;text-align:center;background-color:rgba(77,97,255,0.05);padding:15px 30px;margin-top:-30px;margin-right:-30px;margin-left:-30px;border-style:solid;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0;',
  '_css_input_textarea' => 'font-size:14px;color:#636363;padding-right:15px;padding-left:15px;border-style:solid;border-radius:20px;',
  'logo' => 'https://blogg.arvixorcapital.com/wp-content/uploads/2018/02/logo-2n.png',
  'social' => 
  array (
    0 => 
    array (
      'title' => 'Facebook',
      'icon' => 'fa fa-facebook',
      'link' => 'https://facebook.com/Codevz',
    ),
    1 => 
    array (
      'title' => 'Twitter',
      'icon' => 'fa fa-twitter',
      'link' => 'https://twitter.com/codevz2',
    ),
    2 => 
    array (
      'title' => 'Instagram',
      'icon' => 'fa fa-instagram',
      'link' => 'https://instagram.com/codevz/',
    ),
  ),
  'social_hover_fx' => 'cz_social_fx_4',
  'social_color_mode' => 'cz_social_colored_bg_hover',
  'social_inline_title' => false,
  '_css_social_a' => 'font-size:16px;color:#ffffff;background-color:rgba(255,255,255,0.05);padding:5px;margin-right:3px;margin-left:4px;border-style:solid;border-radius:50px;',
  'header_1_left' => 
  array (
    0 => 
    array (
      'element' => 'logo',
      'element_id' => 'header_1_left',
      'margin' => 
      array (
        'top' => '25px',
        'bottom' => '10px',
        'left' => '-10px',
      ),
      'logo_width' => '220px',
      'menu_location' => 'primary',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
    ),
    1 => 
    array (
      'element' => 'menu',
      'element_id' => 'header_1_left',
      'margin' => 
      array (
        'top' => '34px',
        'bottom' => '20px',
        'left' => '40px',
      ),
      'menu_location' => 'primary',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
    ),
  ),
  'header_1_right' => 
  array (
    0 => 
    array (
      'element' => 'button',
      'element_id' => 'header_1_right',
      'margin' => 
      array (
        'top' => '32px',
        'bottom' => '20px',
      ),
      'menu_location' => 'primary',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'btn_title' => '+1 (800) 333 44 55',
      'btn_link' => 'tel:0018003334455',
      'sk_btn' => 'font-size:14px;font-weight:700;padding:6px 20px;',
      'sk_btn_hover' => 'color:#4d61ff;background-color:#ffffff;',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
    ),
    1 => 
    array (
      'element' => 'social',
      'element_id' => 'header_1_right',
      'margin' => 
      array (
        'top' => '33px',
        'right' => '4px',
      ),
      'menu_location' => 'primary',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
    ),
  ),
  '_css_row_header_1' => 'padding-top:10px;box-shadow:0px 0px 0px 0px #000;',
  '_css_menu_a_header_1' => 'font-size:14px;color:#ffffff;text-transform:uppercase;padding-right:5px;padding-left:5px;margin-right:10px;margin-left:10px;',
  '_css_menu_a_hover_header_1' => 'color:#ffffff;',
  '_css_menu_a_hover_before_header_1' => '_class_menu_fx:cz_menu_fx_left_to_right;width:calc( 100% + 6px );height:10px;border-style:solid;border-width:0px;border-radius:25px;bottom:10px;left:-3px;',
  'menus_indicator_header_1' => 'fa fa-angle-down',
  '_css_menus_separator_header_1' => 'color:rgba(255,255,255,0.2);',
  '_css_menu_ul_header_1' => 'background-color:#4d61ff;width:200px;padding:24px 2px 24px 6px;margin-left:27px;border-radius:15px;',
  '_css_menu_ul_a_header_1' => 'font-size:12px;color:rgba(255,255,255,0.61);text-transform:uppercase;border-color:rgba(255,255,255,0.01);',
  '_css_menu_ul_a_hover_header_1' => 'color:#ffffff;',
  'menus_indicator2_header_1' => 'fa fa-angle-right',
  '_css_menu_a_header_2' => 'padding-right:6px;padding-left:6px;margin-right:20px;',
  '_css_menu_a_hover_header_2' => 'color:#ffffff;',
  '_css_menu_a_hover_before_header_2' => '_class_menu_fx:cz_menu_fx_fade_in;border-style:solid;border-width:0px 0px 0px 0px;border-radius:4px;',
  'menus_indicator_header_2' => 'fa fa-angle-down',
  '_css_menu_ul_header_2' => 'background-color:#4d61ff;margin:1px   12px;border-style:solid;border-radius:4px;',
  '_css_menu_ul_a_header_2' => 'color:#ffffff;',
  '_css_menu_ul_a_hover_header_2' => 'color:#e2e2e2;',
  'menus_indicator2_header_2' => 'fa fa-angle-right',
  'menus_indicator_header_3' => 'fa fa-angle-down',
  'menus_indicator2_header_3' => 'fa fa-angle-right',
  'sticky_header' => '1',
  'smart_sticky' => true,
  '_css_container_header_5' => 'background-color:rgba(17,17,17,0.8);',
  'menus_indicator_header_5' => 'fa fa-angle-down',
  'menus_indicator2_header_5' => 'fa fa-angle-right',
  'header_4_left' => 
  array (
    0 => 
    array (
      'element' => 'logo',
      'element_id' => 'header_4_left',
      'logo_width' => '160px',
      'menu_location' => 'primary',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
      'margin' => 
      array (
        'top' => '24px',
        'bottom' => '12px',
      ),
    ),
  ),
  'header_4_right' => 
  array (
    0 => 
    array (
      'element' => 'menu',
      'element_id' => 'header_4_right',
      'menu_location' => 'primary',
      'menu_type' => 'offcanvas_menu_right',
      'sk_menu_icon' => 'color:#ffffff;background-color:#4d61ff;border-radius:100px;',
      'sk_menu_icon_hover' => 'color:#4d61ff;background-color:#ffffff;',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
      'margin' => 
      array (
        'top' => '23px',
        'bottom' => '20px',
      ),
    ),
  ),
  '_css_menu_container_header_4' => 'background-size:cover;background-image:linear-gradient(90deg,rgba(0,0,0,0.3),rgba(0,0,0,0.3)),url(https://blogg.arvixorcapital.com/wp-content/uploads/2017/08/slider1-1-1.jpg);',
  '_css_menu_a_header_4' => '_class_indicator:fa fa-angle-down;color:rgba(255,255,255,0.75);border-style:solid;border-color:rgba(255,255,255,0.07);',
  '_css_menu_a_hover_header_4' => 'color:#4d61ff;background-color:rgba(255,255,255,0.03);padding-right:25px;padding-left:25px;',
  'menus_indicator_header_4' => 'fa fa-angle-down',
  '_css_menu_ul_a_header_4' => 'color:rgba(255,255,255,0.66);',
  '_css_menu_ul_a_hover_header_4' => 'color:#4d61ff;padding-right:25px;padding-left:25px;',
  'menus_indicator2_header_4' => 'fa fa-angle-down',
  'page_cover' => 'title',
  'page_title' => '8',
  'breadcrumbs_home_icon' => 'fa fa-home',
  'breadcrumbs_separator' => 'fa fa-angle-double-right',
  '_css_page_title' => 'padding:10px  0px ;',
  '_css_page_title_color' => 'font-size:22px;',
  '_css_page_title_breadcrumbs_color' => 'font-size:12px;',
  '_css_breadcrumbs_container' => NULL,
  '_css_breadcrumbs_inner_container' => 'background-color:rgba(255,255,255,0.03);padding:4px 26px 6px 26px;border-style:solid;border-radius:22px;',
  'wp_editor_fonts' => 
  array (
    0 => 
    array (
      'font' => 'Playfair Display',
    ),
  ),
  'footer_layout' => 's3,s3,s3,s3',
  '_css_footer' => 'background-color:#4d61ff;padding-top:50px;padding-bottom:50px;',
  '_css_footer_widget' => 'color:#ffffff;padding:10px 10px 10px 10px;',
  '_css_footer_a' => 'color:#ffffff;',
  '_css_footer_a_hover' => 'color:#c6c6c6;',
  'footer_2_left' => 
  array (
    0 => 
    array (
      'element' => 'icon',
      'element_id' => 'footer_2_left',
      'margin' => 
      array (
        'top' => '20px',
        'bottom' => '20px',
      ),
      'menu_location' => 'primary',
      'it_text' => 'Copyright © %year% Xtra Theme. All Rights Reserved.',
      'sk_it' => 'font-size:13px;color:rgba(255,255,255,0.7);letter-spacing:0px;',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
    ),
  ),
  'footer_2_right' => 
  array (
    0 => 
    array (
      'element' => 'icon',
      'element_id' => 'footer_2_right',
      'margin' => 
      array (
        'top' => '20px',
      ),
      'menu_location' => 'primary',
      'it_text' => 'Contact Us',
      'it_link' => '#',
      'sk_it' => 'font-size:14px;color:rgba(255,255,255,0.8);',
      'sk_it_hover' => 'color:#4d61ff;',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
      'hide_on_mobile' => '1',
    ),
    1 => 
    array (
      'element' => 'line',
      'element_id' => 'footer_2_right',
      'margin' => 
      array (
        'top' => '22px',
      ),
      'menu_location' => 'primary',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_2',
      'wpml_title' => 'translated_name',
      'hide_on_mobile' => '1',
    ),
    2 => 
    array (
      'element' => 'icon',
      'element_id' => 'footer_2_right',
      'margin' => 
      array (
        'top' => '20px',
      ),
      'menu_location' => 'primary',
      'it_text' => 'Privacy Policy',
      'it_link' => '#',
      'sk_it' => 'font-size:14px;color:rgba(255,255,255,0.8);',
      'sk_it_hover' => 'color:#4d61ff;',
      'search_type' => 'form',
      'inview_position_widget' => 'inview_left',
      'shop_plugin' => 'woo',
      'line_type' => 'header_line_1',
      'wpml_title' => 'translated_name',
      'hide_on_mobile' => '1',
    ),
  ),
  'fixed_footer' => false,
  'backtotop' => 'fa fa-angle-up',
  '_css_backtotop' => 'color:#ffffff;background-color:#4d61ff;font-size:14px;border-style:solid;border-radius:50px;',
  'cf7_beside_backtotop' => 'Fixed Contact Form',
  '_css_cf7_beside_backtotop' => 'color:#ffffff;background-color:#4d61ff;font-size:14px;border-style:solid;border-radius:50px;',
  '_css_cf7_beside_backtotop_container' => 'border-style:solid;border-width:1px;border-color:rgba(255,255,255,0.16);border-radius:20px;',
  'meta_data_post' => 
  array (
    0 => 'image',
    1 => 'date',
    2 => 'author',
    3 => 'cats',
    4 => 'tags',
    5 => 'author_box',
    6 => 'next_prev',
  ),
  'related_post' => 'You May Also Like ...',
  'meta_data_portfolio' => 
  array (
    0 => 'date',
    1 => 'cats',
    2 => 'tags',
  ),
  'related_portfolio' => 'You May Also Like ...',
  'primary_portfolio' => 'primary',
  'secondary_portfolio' => 'secondary',
  'page_coverportfolio' => '1',
  'page_titleportfolio' => '1',
  '_css_page_titleportfolio' => NULL,
  '_css_page_title_colorportfolio' => NULL,
  '_css_page_title_breadcrumbs_colorportfolio' => NULL,
  '_css_breadcrumbs_containerportfolio' => NULL,
  '_css_breadcrumbs_inner_containerportfolio' => NULL,
  '_css_right_br_full_containerportfolio' => NULL,
  '_css_sidebar-1_search-2' => NULL,
  '_css_sidebar-1_recent-posts-2' => NULL,
  '_css_sidebar-1_recent-comments-2' => NULL,
  '_css_sidebar-1_archives-2' => NULL,
  '_css_sidebar-1_categories-2' => NULL,
  '_css_sidebar-1_meta-2' => NULL,
  '_css_footer_widget_headlines' => 'font-size:18px;border-style:solid;',
  'page_cover_portfolio' => '1',
  '_css_woo_products_thumbnails' => 'background-color:#222222;padding-top:40px;padding-bottom:40px;border-style:solid;border-width:1px;border-color:rgba(0,0,0,0.08);',
  '_css_backtotop_hover' => 'color:#4d61ff;background-color:#ffffff;',
  '_css_cf7_beside_backtotop_hover' => 'color:#4d61ff;background-color:#ffffff;',
  'page_title_portfolio' => '1',
  '_css_breadcrumbs_container_portfolio' => NULL,
  'page_cover_product' => '1',
  'page_title_product' => '1',
  '_css_breadcrumbs_container_product' => NULL,
  'layout_product' => 'ws',
  'woo_col' => '4',
  '_css_woo_products_title' => 'font-weight:200;',
  '_css_woo_products_stars' => 'display:none;',
  '_css_woo_products_add_to_cart' => 'color:#ffffff;background-color:rgba(63,81,181,0.68);border-style:solid;opacity:0.5;',
  '_css_woo_products_onsale' => 'font-size:14px;color:#ffffff;line-height:1em;background-color:rgba(77,97,255,0.2);width:1em;height:1em;padding:11px 12px;border-radius:50px;top:15px;left:15px;',
  '_css_woo_products_price' => 'font-size:14px;color:#ffffff;font-weight:800;background-color:rgba(77,97,255,0.2);margin-left:-1px;top:15px;right:15px;',
  '_css_woo_product_price' => 'font-size:28px;color:#4d61ff;',
  '_css_woo_buttons' => 'color:#ffffff;background-color:#4d61ff;',
  '_css_woo_buttons_hover' => 'color:#4d61ff;background-color:rgba(77,97,255,0.1);',
  '_css_primary_search-2' => NULL,
  '_css_primary_recent-posts-2' => NULL,
  '_css_primary_recent-comments-2' => NULL,
  '_css_primary_archives-2' => NULL,
  '_css_primary_categories-2' => NULL,
  '_css_primary_meta-2' => NULL,
  '_css_footer-1_text-2' => NULL,
  '_css_footer-2_nav_menu-2' => NULL,
  '_css_footer-3_nav_menu-3' => NULL,
  '_css_footer-4_nav_menu-4' => NULL,
  'posts_per_page_portfolio' => '6',
  'cf7_beside_backtotop_icon' => 'fa fa-envelope-o',
  'readmore' => 'Read More',
  'readmore_icon' => 'fa fa-angle-right',
  '_css_overal_content_block' => NULL,
  '_css_all_img_tags' => 'border-radius:10px;',
  '_css_tags_categories' => 'background-color:rgba(255,255,255,0.05);border-style:solid;border-width:0px 0px 0px 0px;border-radius:20px;',
  '_css_tags_categories_hover' => 'color:#ffffff;background-color:#4d61ff;',
  '_css_menu_ul_ul_header_1' => 'margin-top:-24px;margin-left:4px;',
  'related_post_col' => 's6',
  'related_post_ppp' => '2',
  '_css_readmore' => 'color:#ffffff;background-color:rgba(77,97,255,0.2);border-radius:99px;',
  '_css_readmore_hover' => 'color:#ffffff;background-color:#4d61ff;',
  '_css_readmore_i' => 'color:#ffffff;background-color:rgba(77,97,255,0.26);margin-top:-1px;margin-right:10px;margin-left:2px;border-radius:99px;RTLmargin:-1px 2px 0 10px;RTL',
  '_css_readmore_hover_i' => 'color:#4d61ff;background-color:#ffffff;',
  'columns_portfolio' => '3',
  'template_style_portfolio' => '1',
  '_css_template_bg_portfolio' => NULL,
  '_css_template_color_portfolio' => NULL,
  'related_portfolio_col' => 's4',
  'related_portfolio_ppp' => '3',
  'woo_template' => '2',
  'woo_related_col' => '3',
  '_css_woo_products_add_to_cart_hover' => 'color:#4d61ff;background-color:#fcfcfc;',
  '_css_primary_tag_cloud-2' => NULL,
  '_css_primary_codevzinstagram-2' => NULL,
  '_css_primary_codevzsimpleads-2' => NULL,
  '_css_footer-1_codevzpagecontent-2' => NULL,
  '_css_footer-2_codevzcustommenulist2-2' => NULL,
  '_css_footer-3_codevzpagecontent-3' => NULL,
  '_css_footer-4_codevzpagecontent-4' => NULL,
  'nicescroll' => false,
  'nicescroll_opt' => 
  array (
    0 => 
    array (
      'cursorcolor' => '#4d61ff',
      'background' => 'rgba(77,97,255,0.1)',
      'cursoropacitymin' => '1',
      'cursoropacitymax' => '1',
      'cursorwidth' => '6px',
      'cursorborderradius' => '16px',
    ),
  ),
  'sticky' => 1,
  'prev_post' => 'Previous',
  'next_post' => 'Next',
  'related_posts_post' => 'Related Posts',
  '_css_post_image' => 'border-radius:10px;box-shadow:-20px 20px 1px 0px rgba(77,97,255,0.2);RTLbox-shadow: 20px 20px 1px rgba(77,97,255,0.2);RTL',
  '_css_overall_post' => 'padding-bottom:50px;',
  '_css_woo_products_result_count' => 'font-size:14px;background-color:rgba(255,255,255,0.03);padding:8px 30px;border-radius:50px;',
  '_css_portfolio_title' => 'color:#ffffff;',
  '_css_portfolio_meta' => 'font-size:14px;',
  '_css_select' => 'border-radius:20px;',
  '_css_select_dropdown' => 'border-radius:20px;',
  'wp_login_logo' => 'https://blogg.arvixorcapital.com/wp-content/uploads/2017/08/logo-2-1.png',
  '_wp_login_body' => 'background-color:#000000;',
  '_wp_login_links' => 'color:#ffffff;',
  '_css_menu_li_header_4' => 'border-style:solid;',
  '_css_menu_indicator_a_header_1' => '_class_indicator:fa fa-angle-down;',
  '_css_menu_ul_indicator_a_header_1' => '_class_indicator:fa fa-angle-right;',
  'social_tooltip' => 'cz_tooltip cz_tooltip_up',
  '_css_social_tooltip' => 'color:#ffffff;background-color:#4d61ff;padding-top:7px;padding-bottom:7px;border-radius:50px;',
  'rtl' => false,
  'fonts_out' => 
  array (
    0 => 'font-family: "Open Sans";',
  ),
  'breakpoint_2' => '768px',
  'breakpoint_3' => '480px',
  '404_msg' => 'Page not found!',
  '404_btn' => 'Back to Homepage',
  'vc_disable_modules' => 
  array (
    0 => 'vc_wp_search',
    1 => 'vc_wp_meta',
    2 => 'vc_wp_recentcomments',
    3 => 'vc_wp_calendar',
    4 => 'vc_wp_pages',
    5 => 'vc_wp_tagcloud',
    6 => 'vc_wp_custommenu',
    7 => 'vc_wp_text',
    8 => 'vc_wp_posts',
    9 => 'vc_wp_categories',
    10 => 'vc_wp_archives',
    11 => 'vc_wp_rss',
  ),
  'template_style' => '1',
  'post_excerpt' => '20',
  'not_found' => 'Not found!',
  'cm_disabled' => 'Comments are disabled.',
  '_css_post_meta_overall' => 'font-size:12px;',
  '_css_post_avatar' => 'width:36px;height:36px;border-radius:99px;',
  '_css_post_excerpt' => 'color:#969696;',
  'no_comment' => 'No comment',
  'comment' => 'Comment',
  'comments' => 'Comments',
  '_css_single_con' => 'background-color:rgba(255,255,255,0.02);padding:30px;border-radius:10px;',
  '_css_single_title' => 'font-size:26px;color:#ffffff;background-color:rgba(77,97,255,0.05);padding:20px 30px;margin:-30px -30px 30px;border-style:solid;border-bottom-width:1px;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0;box-shadow:0px 0px 0px 0px #000000;',
  '_css_next_prev_con' => 'background-color:rgba(255,255,255,0.02);padding:30px;border-radius:10px;',
  '_css_next_prev_icons' => 'background-color:#4d61ff;',
  '_css_next_prev_icons_hover' => 'color:#4d61ff;background-color:#ffffff;',
  '_css_next_prev_surtitle' => 'color:#8e8e8e;',
  '_css_related_posts_con' => 'background-color:rgba(255,255,255,0.02);padding:30px 30px 1px;border-radius:10px;',
  '_css_related_posts_sec_title' => 'font-size:16px;color:#ffffff;text-align:center;background-color:rgba(77,97,255,0.05);padding:15px 30px;margin:-30px -30px 30px;border-style:solid;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0;',
  '_css_related_posts' => 'margin-right:10px;margin-left:10px;',
  '_css_related_posts_img' => 'margin-bottom:40px;',
  '_css_related_posts_meta' => 'font-size:12px;',
  '_css_single_comments_title' => 'font-size:16px;color:#ffffff;text-align:center;background-color:rgba(77,97,255,0.05);padding:15px 30px;margin:-30px -30px 30px;border-style:solid;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0;',
  '_css_single_comments_li' => 'border-radius:10px;',
  'search_title_prefix' => 'Search result for:',
  'primary_search' => 'primary',
  'secondary_search' => 'secondary',
  'cols_portfolio' => 's4',
  'related_posts_portfolio' => 'Related Posts ...',
  'css_out' => '.row,section.elementor-section.elementor-section-boxed>.elementor-container{width: 1270px}.inner_layout .e-con {--content-width: min(100%, 1270px)}

/* Theme color */a:hover, .sf-menu > .cz.current_menu > a, .sf-menu > .cz .cz.current_menu > a,.sf-menu > .current-menu-parent > a,.comment-text .star-rating span {color: #4d61ff} 
form button, .button, #edd-purchase-button, .edd-submit, .edd-submit.button.blue, .edd-submit.button.blue:hover, .edd-submit.button.blue:focus, [type=submit].edd-submit, .sf-menu > .cz > a:before,.sf-menu > .cz > a:before,
.post-password-form input[type="submit"], .wpcf7-submit, .submit_user, 
#commentform #submit, .commentlist li.bypostauthor > .comment-body:after,.commentlist li.comment-author-admin > .comment-body:after, 
 .pagination .current, .pagination > b, .pagination a:hover, .page-numbers .current, .page-numbers a:hover, .pagination .next:hover, 
.pagination .prev:hover, input[type=submit], .sticky:before, .commentlist li.comment-author-admin .fn,
input[type=submit],input[type=button],.cz_header_button,.cz_default_portfolio a,
.cz_readmore, .more-link, a.cz_btn, .cz_highlight_1:after, div.cz_btn ,.woocommerce input.button.alt.woocommerce #respond input#submit, .woocommerce a.button, .woocommerce button.button, .woocommerce input.button,.woocommerce .woocommerce-error .button,.woocommerce .woocommerce-info .button, .woocommerce .woocommerce-message .button, .woocommerce-page .woocommerce-error .button, .woocommerce-page .woocommerce-info .button, .woocommerce-page .woocommerce-message .button,#add_payment_method table.cart input, .woocommerce-cart table.cart input:not(.input-text), .woocommerce-checkout table.cart input,.woocommerce input.button:disabled, .woocommerce input.button:disabled[disabled],#add_payment_method table.cart input, #add_payment_method .wc-proceed-to-checkout a.checkout-button, .woocommerce-cart .wc-proceed-to-checkout a.checkout-button, .woocommerce-checkout .wc-proceed-to-checkout a.checkout-button,.woocommerce #payment #place_order, .woocommerce-page #payment #place_order,.woocommerce input.button.alt,.woocommerce #respond input#submit.alt:hover, .woocommerce button.button.alt:hover, .woocommerce input.button.alt:hover,.woocommerce #respond input#submit.alt:hover, .woocommerce a.button.alt:hover, .woocommerce nav.woocommerce-pagination ul li a:focus, .woocommerce nav.woocommerce-pagination ul li a:hover, .woocommerce nav.woocommerce-pagination ul li span.current, .widget_product_search #searchsubmit,.woocommerce .widget_price_filter .ui-slider .ui-slider-range, .woocommerce .widget_price_filter .ui-slider .ui-slider-handle, .woocommerce #respond input#submit, .woocommerce a.button, .woocommerce button.button, .woocommerce input.button, .woocommerce div.product form.cart .button, .xtra-product-icons,.woocommerce button.button.alt {background-color: #4d61ff}
.cs_load_more_doing, div.wpcf7 .wpcf7-form .ajax-loader {border-right-color: #4d61ff}
input:focus,textarea:focus,select:focus {border-color: #4d61ff !important}
::selection {background-color: #4d61ff;color: #fff}
::-moz-selection {background-color: #4d61ff;color: #fff}

/* Dynamic  */html,body{background-color:#151719}#layout{border-style:solid;border-radius:4px}form button,.comment-form button,a.cz_btn,div.cz_btn,a.cz_btn_half_to_fill:before,a.cz_btn_half_to_fill_v:before,a.cz_btn_half_to_fill:after,a.cz_btn_half_to_fill_v:after,a.cz_btn_unroll_v:before, a.cz_btn_unroll_h:before,a.cz_btn_fill_up:before,a.cz_btn_fill_down:before,a.cz_btn_fill_left:before,a.cz_btn_fill_right:before,.wpcf7-submit,input[type=submit],input[type=button],.form-submit #submit,.button,.cz_header_button,.woocommerce a.button,.woocommerce input.button,.woocommerce #respond input#submit.alt,.woocommerce a.button.alt,.woocommerce button.button.alt,.woocommerce input.button.alt,.woocommerce #respond input#submit, .woocommerce a.button, .woocommerce button.button, .woocommerce input.button, #edd-purchase-button, .edd-submit, [type=submit].edd-submit, .edd-submit.button.blue,.woocommerce #payment #place_order, .woocommerce-page #payment #place_order,.woocommerce button.button:disabled, .woocommerce button.button:disabled[disabled], .woocommerce a.button.wc-forward,.wp-block-search .wp-block-search__button,.woocommerce-message a.restore-item.button{font-weight:700;padding:12px 25px;border-style:solid;border-radius:50px;box-shadow:0px 0px 0px 0px #000}form button:hover,.comment-form button:hover,a.cz_btn:hover,div.cz_btn:hover,a.cz_btn_half_to_fill:hover:before, a.cz_btn_half_to_fill_v:hover:before,a.cz_btn_half_to_fill:hover:after, a.cz_btn_half_to_fill_v:hover:after,a.cz_btn_unroll_v:after, a.cz_btn_unroll_h:after,a.cz_btn_fill_up:after,a.cz_btn_fill_down:after,a.cz_btn_fill_left:after,a.cz_btn_fill_right:after,.wpcf7-submit:hover,input[type=submit]:hover,input[type=button]:hover,.form-submit #submit:hover,.button:hover,.cz_header_button:hover,.woocommerce a.button:hover,.woocommerce input.button:hover,.woocommerce #respond input#submit.alt:hover,.woocommerce a.button.alt:hover,.woocommerce button.button.alt:hover,.woocommerce input.button.alt:hover,.woocommerce #respond input#submit:hover, .woocommerce a.button:hover, .woocommerce button.button:hover, .woocommerce input.button:hover, #edd-purchase-button:hover, .edd-submit:hover, [type=submit].edd-submit:hover, .edd-submit.button.blue:hover, .edd-submit.button.blue:focus,.woocommerce #payment #place_order:hover, .woocommerce-page #payment #place_order:hover,.woocommerce div.product form.cart .button:hover,.woocommerce button.button:disabled:hover, .woocommerce button.button:disabled[disabled]:hover, .woocommerce a.button.wc-forward:hover,.wp-block-search .wp-block-search__button:hover,.woocommerce-message a.restore-item.button:hover{color:#4d61ff;background-color:#ffffff}.widget{background-color:rgba(255,255,255,0.02);margin-bottom:30px;border-radius:10px}.widget > .codevz-widget-title, .sidebar_inner .widget_block > div > div > h2{font-size:16px;color:#ffffff;text-align:center;background-color:rgba(77,97,255,0.05);padding:15px 30px;margin-top:-30px;margin-right:-30px;margin-left:-30px;border-style:solid;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0}input,textarea,select,.qty,.woocommerce-input-wrapper .select2-selection--single,#add_payment_method table.cart td.actions .coupon .input-text, .woocommerce-cart table.cart td.actions .coupon .input-text, .woocommerce-checkout table.cart td.actions .coupon .input-text,.woocommerce form .form-row .input-text, .woocommerce form .form-row select{font-size:14px;color:#636363;padding-right:15px;padding-left:15px;border-style:solid;border-radius:20px}.elms_row .cz_social a, .fixed_side .cz_social a, #xtra-social-popup [class*="xtra-social-type-"] a{font-size:16px;color:#ffffff;background-color:rgba(255,255,255,0.05);padding:5px;margin-right:3px;margin-left:4px;border-style:solid;border-radius:50px}.header_1 .row{padding-top:10px;box-shadow:0px 0px 0px 0px #000}#menu_header_1 > .cz > a{font-size:14px;color:#ffffff;text-transform:uppercase;padding-right:5px;padding-left:5px;margin-right:10px;margin-left:10px}#menu_header_1 > .cz > a:hover,#menu_header_1 > .cz:hover > a,#menu_header_1 > .cz.current_menu > a,#menu_header_1 > .current-menu-parent > a{color:#ffffff}#menu_header_1 > .cz > a:before{width:calc( 100% + 6px );height:10px;border-style:solid;border-width:0px;border-radius:25px;bottom:10px;left:-3px}#menu_header_1 > .cz:after{color:rgba(255,255,255,0.2)}#menu_header_1 .cz .sub-menu:not(.cz_megamenu_inner_ul),#menu_header_1 .cz_megamenu_inner_ul .cz_megamenu_inner_ul{background-color:#4d61ff;width:200px;padding:24px 2px 24px 6px;margin-left:27px;border-radius:15px}#menu_header_1 .cz .cz a{font-size:12px;color:rgba(255,255,255,0.61);text-transform:uppercase;border-color:rgba(255,255,255,0.01)}#menu_header_1 .cz .cz a:hover,#menu_header_1 .cz .cz:hover > a,#menu_header_1 .cz .cz.current_menu > a,#menu_header_1 .cz .current_menu > .current_menu{color:#ffffff}#menu_header_2 > .cz > a{padding-right:6px;padding-left:6px;margin-right:20px}#menu_header_2 > .cz > a:hover,#menu_header_2 > .cz:hover > a,#menu_header_2 > .cz.current_menu > a,#menu_header_2 > .current-menu-parent > a{color:#ffffff}#menu_header_2 > .cz > a:before{border-style:solid;border-width:0px 0px 0px 0px;border-radius:4px}#menu_header_2 .cz .sub-menu:not(.cz_megamenu_inner_ul),#menu_header_2 .cz_megamenu_inner_ul .cz_megamenu_inner_ul{background-color:#4d61ff;margin:1px   12px;border-style:solid;border-radius:4px}#menu_header_2 .cz .cz a{color:#ffffff}#menu_header_2 .cz .cz a:hover,#menu_header_2 .cz .cz:hover > a,#menu_header_2 .cz .cz.current_menu > a,#menu_header_2 .cz .current_menu > .current_menu{color:#e2e2e2}.onSticky{background-color:rgba(17,17,17,0.8) !important}#menu_header_4{background-size:cover;background-image:linear-gradient(90deg,rgba(0,0,0,0.3),rgba(0,0,0,0.3)),url(https://blogg.arvixorcapital.com/wp-content/uploads/2017/08/slider1-1-1.jpg)}#menu_header_4 > .cz > a{color:rgba(255,255,255,0.75);border-style:solid;border-color:rgba(255,255,255,0.07)}#menu_header_4 > .cz > a:hover,#menu_header_4 > .cz:hover > a,#menu_header_4 > .cz.current_menu > a,#menu_header_4 > .current-menu-parent > a{color:#4d61ff;background-color:rgba(255,255,255,0.03);padding-right:25px;padding-left:25px}#menu_header_4 .cz .cz a{color:rgba(255,255,255,0.66)}#menu_header_4 .cz .cz a:hover,#menu_header_4 .cz .cz:hover > a,#menu_header_4 .cz .cz.current_menu > a,#menu_header_4 .cz .current_menu > .current_menu{color:#4d61ff;padding-right:25px;padding-left:25px}.page_title,.header_onthe_cover .page_title{padding:10px  0px }.page_title .codevz-section-title{font-size:22px}.breadcrumbs a,.breadcrumbs i{font-size:12px}.breadcrumbs{background-color:rgba(255,255,255,0.03);padding:4px 26px 6px 26px;border-style:solid;border-radius:22px}.cz_middle_footer{background-color:#4d61ff;padding-top:50px;padding-bottom:50px}.footer_widget{color:#ffffff;padding:10px 10px 10px 10px}.cz_middle_footer a{color:#ffffff}.cz_middle_footer a:hover{color:#c6c6c6}i.backtotop{color:#ffffff;background-color:#4d61ff;font-size:14px;border-style:solid;border-radius:50px}i.fixed_contact{color:#ffffff;background-color:#4d61ff;font-size:14px;border-style:solid;border-radius:50px}div.fixed_contact{border-style:solid;border-width:1px;border-color:rgba(255,255,255,0.16);border-radius:20px}.footer_widget > .codevz-widget-title, footer .widget_block > div > div > h2{font-size:18px;border-style:solid}.woocommerce ul.products li.product .cz_image_in{background-color:#222222;padding-top:40px;padding-bottom:40px;border-style:solid;border-width:1px;border-color:rgba(0,0,0,0.08)}i.backtotop:hover{color:#4d61ff;background-color:#ffffff}i.fixed_contact:hover,i.fixed_contact_active{color:#4d61ff;background-color:#ffffff}.woocommerce ul.products li.product .woocommerce-loop-category__title, .woocommerce ul.products li.product .woocommerce-loop-product__title, .woocommerce ul.products li.product h3,.woocommerce.woo-template-2 ul.products li.product .woocommerce-loop-category__title, .woocommerce.woo-template-2 ul.products li.product .woocommerce-loop-product__title, .woocommerce.woo-template-2 ul.products li.product h3{font-weight:200}.woocommerce ul.products li.product .star-rating{display:none}.woocommerce ul.products li.product .button.add_to_cart_button, .woocommerce ul.products li.product .button[class*="product_type_"]{color:#ffffff;background-color:rgba(63,81,181,0.68);border-style:solid;opacity:0.5}.woocommerce span.onsale, .woocommerce ul.products li.product .onsale,.woocommerce.single span.onsale, .woocommerce.single ul.products li.product .onsale{font-size:14px;color:#ffffff;line-height:1em;background-color:rgba(77,97,255,0.2);width:1em;height:1em;padding:11px 12px;border-radius:50px;top:15px;left:15px}.woocommerce ul.products li.product .price{font-size:14px;color:#ffffff;font-weight:800;background-color:rgba(77,97,255,0.2);margin-left:-1px;top:15px;right:15px}.woocommerce div.product .summary > p.price, .woocommerce div.product .summary > span.price{font-size:28px;color:#4d61ff}.page_content img, a.cz_post_image img, footer img, .cz_image_in, .wp-block-gallery figcaption, .cz_grid .cz_grid_link{border-radius:10px}.tagcloud a, .widget .tagcloud a, .cz_post_cat a, .cz_post_views a{background-color:rgba(255,255,255,0.05);border-style:solid;border-width:0px 0px 0px 0px;border-radius:20px}.tagcloud a:hover, .widget .tagcloud a:hover, .cz_post_cat a:hover, .cz_post_views a:hover{color:#ffffff;background-color:#4d61ff}#menu_header_1 .sub-menu .sub-menu:not(.cz_megamenu_inner_ul){margin-top:-24px;margin-left:4px}.cz-cpt-post .cz_readmore, .cz-cpt-post .more-link{color:#ffffff;background-color:rgba(77,97,255,0.2);border-radius:99px}.cz-cpt-post .cz_readmore:hover, .cz-cpt-post .more-link:hover{color:#ffffff;background-color:#4d61ff}.cz-cpt-post .cz_readmore i, .cz-cpt-post .more-link i{color:#ffffff;background-color:rgba(77,97,255,0.26);margin-top:-1px;margin-right:10px;margin-left:2px;border-radius:99px}.rtl.cz-cpt-post .cz_readmore i,.rtl.cz-cpt-post .more-link i{margin:-1px 2px 0 10px}.woocommerce ul.products li.product .button.add_to_cart_button:hover, .woocommerce ul.products li.product .button[class*="product_type_"]:hover{color:#4d61ff;background-color:#fcfcfc}.cz-cpt-post .cz_post_image, .cz-cpt-post .cz_post_svg{border-radius:10px;box-shadow:-20px 20px 1px 0px rgba(77,97,255,0.2)}.rtl.cz-cpt-post .cz_post_image,.rtl.cz-cpt-post .cz_post_svg{box-shadow: 20px 20px 1px rgba(77,97,255,0.2)}.cz-cpt-post .cz_default_loop > div{padding-bottom:50px}.woocommerce .woocommerce-result-count{font-size:14px;background-color:rgba(255,255,255,0.03);padding:8px 30px;border-radius:50px}.cz-cpt-portfolio .cz_default_loop .cz_post_title h3{color:#ffffff}#menu_header_4 > .cz{border-style:solid}[class*="cz_tooltip_"] [data-title]:after{color:#ffffff;background-color:#4d61ff;padding-top:7px;padding-bottom:7px;border-radius:50px}.cz-cpt-post .cz_default_loop .cz_post_meta{font-size:12px}.cz-cpt-post .cz_default_loop .cz_post_author_avatar img{width:36px;height:36px;border-radius:99px}.cz-cpt-post .cz_default_loop .cz_post_excerpt{color:#969696}.single_con{background-color:rgba(255,255,255,0.02);padding:30px;border-radius:10px}.single .content .xtra-post-title{font-size:26px;color:#ffffff;background-color:rgba(77,97,255,0.05);padding:20px 30px;margin:-30px -30px 30px;border-style:solid;border-bottom-width:1px;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0;box-shadow:0px 0px 0px 0px #000000}.next_prev{background-color:rgba(255,255,255,0.02);padding:30px;border-radius:10px}.next_prev .previous i,.next_prev .next i{background-color:#4d61ff}.next_prev .previous:hover i,.next_prev .next:hover i{color:#4d61ff;background-color:#ffffff}.next_prev h4 small{color:#8e8e8e}.xtra-comments,.content.cz_related_posts,.cz_author_box,.related.products,.upsells.products,.up-sells.products,.woocommerce-page .cart-collaterals .cart_totals,.woocommerce-page #customer_details,.woocommerce-page .codevz-checkout-details,.woocommerce-page .woocommerce-order-details,.woocommerce-page .woocommerce-customer-details,.woocommerce-page .cart-collaterals .cross-sells,.woocommerce-account .cz_post_content > .woocommerce{background-color:rgba(255,255,255,0.02);padding:30px 30px 1px;border-radius:10px}#comments > h3,.content.cz_related_posts > h4,.content.cz_author_box > h4,.related.products > h2,.upsells.products > h2,.up-sells.products > h2,.up-sells.products > h2,.woocommerce-page .cart-collaterals .cart_totals > h2,.woocommerce-page #customer_details > div:first-child > div:first-child > h3:first-child,.woocommerce-page .codevz-checkout-details > h3,.woocommerce-page .woocommerce-order-details > h2,.woocommerce-page .woocommerce-customer-details > h2,.woocommerce-page .cart-collaterals .cross-sells > h2{font-size:16px;color:#ffffff;text-align:center;background-color:rgba(77,97,255,0.05);padding:15px 30px;margin:-30px -30px 30px;border-style:solid;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0}.cz_related_posts .cz_related_post > div{margin-right:10px;margin-left:10px}.cz_related_posts .cz_related_post .cz_post_image{margin-bottom:40px}.cz_related_posts .cz_related_post_date{font-size:12px}.xtra-comments .commentlist li article{border-radius:10px}.cz-cpt-post article .cz_post_icon{color:#ffffff;background-color:#4d61ff}.cz-cpt-post .cz_readmore:hover i, .cz-cpt-post .more-link:hover i{background-color:rgba(0,0,0,0.1)}.single_con .tagcloud a:first-child, .single_con .cz_post_cat a:first-child, .cz_post_views a:first-child{color:#4d61ff;background-color:rgba(77,97,255,0.1)}.footer_widget > .codevz-widget-title:before, footer .widget_block > div > div > h2:before{background-color:#ffffff;width:50px;height:1px;bottom:-1px}.products .product .xtra-product-icons{font-size:14px;background-color:rgba(77,97,255,0.2);padding:2px;margin-right:5px;margin-left:5px;border-radius:99px}.woocommerce .cart .xtra-product-icons-wishlist{border-radius:99px}.woocommerce div.product .woocommerce-tabs ul.tabs li.active{color:#ffffff;background-color:rgba(77,97,255,0.05);border-style:solid;border-width:0px 0px 1px;border-color:rgba(77,97,255,0.31)}.woocommerce div.product .woocommerce-tabs .panel{background-color:rgba(255,255,255,0.02);border-style:none;border-width:1px 0px 0px;border-color:rgba(77,97,255,0.31);border-radius:5px}.woocommerce div.product .woocommerce-tabs ul.tabs li{background-color:rgba(255,255,255,0.01);margin-top:50px;border-style:solid;border-bottom-width:1px;border-color:transparent;border-radius:5px 5px 0 0}div.xtra-share{background-color:rgba(255,255,255,0.02);padding:60px 20px 20px;border-style:none;border-radius:10px;display:flex}div.xtra-share a{width:100%;border-radius:5px}.products .product .xtra-add-to-wishlist{border-radius:99px}.products .product .xtra-add-to-wishlist:hover{color:#4d61ff;background-color:#ffffff}.products .product .xtra-product-quick-view{border-radius:99px}.products .product .xtra-product-quick-view:hover{color:#4d61ff;background-color:#ffffff}.woocommerce .cart .xtra-product-icons-wishlist:hover{color:#4d61ff;background-color:#ffffff}#xtra_quick_view .cz_popup_in, #xtra_wish_compare .cz_popup_in{color:#ffffff;background-color:#1c1e20;border-radius:10px}.single .xtra-post-title-date a, .single .xtra-post-title-date .xtra-post-views{color:#919191;margin-top:25px}.single .xtra-post-title-date a:hover{color:#4d61ff}div.xtra-share:before{font-size:16px;text-align:center;font-weight:700;background-color:rgba(77,97,255,0.05);width:100%;padding-top:6px;padding-bottom:6px;border-style:solid;border-width:0px 0px 1px;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0;position:absolute;top:0px;left:0px}.quantity-down{color:#8c8c8c;padding:5px;margin-left:10px;border-radius:100px}.rtl .quantity-down{margin-left:0px;margin-right:10px}.woocommerce .quantity .qty{width:130px;margin-right:-38px;margin-left:-38px}.quantity-down:hover{color:#ffffff;background-color:#4d61ff}.quantity-up{color:#7f7f7f;padding:5px;margin-right:10px;border-radius:100px}.rtl .quantity-up{margin-right:0px;margin-left:10px}.quantity-up:hover{color:#ffffff;background-color:#4d61ff}.xtra-mobile-menu-text{font-size:13px;color:#969696;padding-top:10px;padding-bottom:20px}li.xtra-mobile-menu-additional .cz_social a{font-size:18px;background-color:rgba(255,255,255,0.08);padding:5px;margin-right:5px;margin-left:5px;border-radius:100px}.xtra-fixed-mobile-nav > a:hover,.xtra-fixed-mobile-nav > .xtra-active{color:#ffffff;background-color:#4d61ff}.xtra-fixed-mobile-nav > a i, .xtra-fixed-mobile-nav > a img{text-align:center;background-color:rgba(77,97,255,0.1);padding:10px;margin-bottom:5px;border-radius:100px}.xtra-fixed-mobile-nav > a:hover i, .xtra-fixed-mobile-nav > a:hover img, .xtra-fixed-mobile-nav > .xtra-active i, .xtra-fixed-mobile-nav > .xtra-active img{color:#4d61ff;background-color:#ffffff}.xtra-fixed-mobile-nav{border-radius:20px 20px 0 0;overflow:hidden}

/* Responsive */@media screen and (max-width:1270px){#layout{width:100%!important}#layout.layout_1,#layout.layout_2{width:95%!important}.row{width:90% !important;padding:0}blockquote{padding:20px}footer .elms_center,footer .have_center .elms_left, footer .have_center .elms_center, footer .have_center .elms_right{float:none;display:block;text-align:center;margin:0 auto;flex:unset}}@media screen and (max-width:768px){}@media screen and (max-width:480px){}',
  'layout_post' => 'right',
  'default_featured_image' => true,
  'hover_icon_icon_post' => 'fa czico-109-link-symbol-1',
  '_css_post_hover_icon' => 'color:#ffffff;background-color:#4d61ff;',
  '_css_readmore_i_hover' => 'background-color:rgba(0,0,0,0.1);',
  'post_excerpt_portfolio' => '20',
  'hover_icon_icon_portfolio' => 'fa czico-109-link-symbol-1',
  'readmore_portfolio' => 'Read More',
  'readmore_icon_portfolio' => 'fa fa-angle-right',
  'prev_portfolio' => 'Previous',
  'next_portfolio' => 'Next',
  'no_comment_portfolio' => 'No comment',
  'comment_portfolio' => 'Comment',
  'comments_portfolio' => 'Comments',
  '_css_woo_product_meta_link' => 'border-radius:99px;',
  '_css_woo_product_meta_link_hover' => 'color:#ffffff;background-color:#4d61ff;',
  '_css_tags_categories_icon' => 'color:#4d61ff;background-color:rgba(77,97,255,0.1);',
  'woo_no_products' => 'No products in the cart',
  '_css_footer_widget_headlines_before' => 'background-color:#ffffff;width:50px;height:1px;bottom:-1px;',
  'custom_sidebars' => 
  array (
    0 => false,
  ),
  'woo_wishlist' => true,
  'woo_quick_view' => true,
  '_css_woo_products_icons' => 'font-size:14px;background-color:rgba(77,97,255,0.2);padding:2px;margin-right:5px;margin-left:5px;border-radius:99px;',
  '_css_woo_product_wishlist' => 'border-radius:99px;',
  '_css_woo_product_active_tab' => 'color:#ffffff;background-color:rgba(77,97,255,0.05);border-style:solid;border-width:0px 0px 1px;border-color:rgba(77,97,255,0.31);',
  '_css_woo_product_tab_content' => 'background-color:rgba(255,255,255,0.02);border-style:none;border-width:1px 0px 0px;border-color:rgba(77,97,255,0.31);border-radius:5px;',
  'woo_product_tabs' => 'center',
  '_css_woo_product_tabs' => 'background-color:rgba(255,255,255,0.01);margin-top:50px;border-style:solid;border-bottom-width:1px;border-color:transparent;border-radius:5px 5px 0 0;',
  'post_type' => 
  array (
    0 => 'post',
    1 => 'product',
    2 => 'download',
    3 => 'portfolio',
  ),
  'share' => 
  array (
    0 => 'facebook',
    1 => 'twitter',
    2 => 'pinterest',
    3 => 'whatsapp',
    4 => 'envelope',
  ),
  'share_tooltip' => true,
  'share_color' => 'cz_social_colored_hover',
  '_css_share' => 'background-color:rgba(255,255,255,0.02);padding:60px 20px 20px;border-style:none;border-radius:10px;display:flex;',
  '_css_share_a' => 'width:100%;border-radius:5px;',
  '_css_share_tooltip' => 'color:#ffffff;background-color:#4d61ff;border-radius:99px;',
  '_css_woo_products_wishlist' => 'border-radius:99px;',
  '_css_woo_products_wishlist_hover' => 'color:#4d61ff;background-color:#ffffff;',
  '_css_woo_products_quick_view' => 'border-radius:99px;',
  '_css_woo_products_quick_view_hover' => 'color:#4d61ff;background-color:#ffffff;',
  '_css_woo_product_wishlist_hover' => 'color:#4d61ff;background-color:#ffffff;',
  '_css_woo_products_quick_view_popup' => 'color:#ffffff;background-color:#1c1e20;border-radius:10px;',
  '_css_single_comments_con' => 'background-color:rgba(255,255,255,0.02);padding:30px 30px 1px;border-radius:10px;',
  '_css_single_title_date' => 'color:#919191;margin-top:25px;',
  '_css_single_title_date_hover' => 'color:#4d61ff;',
  'share_box_title' => 'Share it',
  '_css_share_title' => 'font-size:16px;text-align:center;font-weight:700;background-color:rgba(77,97,255,0.05);width:100%;padding-top:6px;padding-bottom:6px;border-style:solid;border-width:0px 0px 1px;border-color:rgba(77,97,255,0.31);border-radius:10px 10px 0 0;position:absolute;top:0px;left:0px;',
  '_css_woo_product_qty_down' => 'color:#8c8c8c;padding:5px;margin-left:10px;border-radius:100px;RTLmargin-left:0px;margin-right:10px;RTL',
  '_css_woo_product_qty' => 'width:130px;margin-right:-38px;margin-left:-38px;',
  '_css_woo_product_qty_down_hover' => 'color:#ffffff;background-color:#4d61ff;',
  '_css_woo_product_qty_up' => 'color:#7f7f7f;padding:5px;margin-right:10px;border-radius:100px;RTLmargin-right:0px;margin-left:10px;RTL',
  '_css_woo_product_qty_up_hover' => 'color:#ffffff;background-color:#4d61ff;',
  'mobile_menu_social' => true,
  'mobile_menu_social_color_mode' => 'cz_social_colored_bg_hover',
  'mobile_menu_text' => '© Copyright [codevz_year]',
  '_css_mm_text' => 'font-size:13px;color:#969696;padding-top:10px;padding-bottom:20px;',
  '_css_mms_icons' => 'font-size:18px;background-color:rgba(255,255,255,0.08);padding:5px;margin-right:5px;margin-left:5px;border-radius:100px;',
  'mobile_fixed_navigation' => true,
  'mobile_fixed_navigation_items' => 
  array (
    0 => 
    array (
      'title' => 'Home',
      'icon_type' => 'icon',
      'icon' => 'fa czico-064-home-4',
      'link' => 'https://www.blogg.arvixorcapital.com/',
    ),
    1 => 
    array (
      'title' => 'Services',
      'icon_type' => 'icon',
      'icon' => 'fas fa-layer-group',
      'link' => 'https://www.blogg.arvixorcapital.com/services/',
    ),
    2 => 
    array (
      'title' => 'Call Us',
      'icon_type' => 'icon',
      'icon' => 'fas fa-phone-alt',
      'link' => 'tel:001818123456789',
    ),
    3 => 
    array (
      'title' => 'Contact',
      'icon_type' => 'icon',
      'icon' => 'fas fa-envelope',
      'link' => 'https://www.blogg.arvixorcapital.com/contact/',
    ),
  ),
  'mobile_fixed_navigation_title' => 'xtra-fixed-mobile-nav-title-column',
  '_css_mfn_a_hover' => 'color:#ffffff;background-color:#4d61ff;',
  '_css_mfn_i' => 'text-align:center;background-color:rgba(77,97,255,0.1);padding:10px;margin-bottom:5px;border-radius:100px;',
  '_css_mfn_i_hover' => 'color:#4d61ff;background-color:#ffffff;',
  '_css_mfn' => 'border-radius:20px 20px 0 0;CDVZoverflow:hidden;CDVZ',
  'default_svg_post' => 1,
  'default_svg_portfolio' => 1,
  'woo_ppp_dropdown' => 1,
  'woo_categories_bar' => '2',
  'woo_product_prev_next_nav' => 1,
  'woo_product_flex_add_to_cart' => 1,
  'woo_product_sticky_add_to_cart' => 1,
  'woo_new_label' => 1,
  'woo_new_label_days' => '14',
  'woo_added_to_cart_notification' => 1,
  'woo_columns_selector' => 1,
  'woo_sale_marquee' => 1,
);